#######################
# Jenkins Build Options
#######################
# User guide for this file: https://github.com/samrocketman/jervis/wiki/User-Guide

language: groovy
jdk: openjdk8

#build library
#gradle doesn't have a retry for assembling dependencies so here's one in bash
install: ./assemble.sh
script: |
  if grep -rlF -- 'new Yaml()' jobs src vars; then
    echo 'ERROR: insecure usage of SnakeYAML detected.' >&2
    exit 1
  fi
  ./gradlew clean check jacocoTestReport Jar groovydoc

env:
  # Jenkins weekly uses Groovy 2.4.12 as of this writing
  - GROOVY_VERSION="2.4.12"
  - GROOVY_VERSION="2.4.20"
  - GROOVY_VERSION="2.5.13"
  # Groovy 3.0 current stable
  - GROOVY_VERSION="3.0.5"

matrix:
  allow_failures:
    - env: GROOVY_VERSION="2.5.13"
    - env: GROOVY_VERSION="3.0.5"

branches:
  only:
    - main
    - jervis_simple

jenkins:
  pipeline_jenkinsfile: assets/Jenkinsfile
  # see YAML anchors and aliases for how this works
  default_stash_axis: &stash_axis
    matrix_axis:
      env: GROOVY_VERSION="2.4.15"
  stash:
    - name: artifacts
      <<: *stash_axis
    - name: html
      <<: *stash_axis
    - name: junit
      <<: *stash_axis
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/*.xml
    html:
      path: build/docs/groovydoc
      reportName: 'Groovy Dev Docs'

########################
# Travis CI Options Only
########################
#Travis CI also uses some options in the Jenkins section above.
#None of the following options are interpreted by Jenkins.

after_success:
  - ./gradlew jacocoTestReport coveralls

#https://docs.travis-ci.com/user/languages/groovy#caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
